# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.  
version: 0.2
phases:
  build:
    commands:
      - pwd  
      - ls
      - du -hs
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'